### ISSUE TITLE
Cannot run code examples

### ISSUE THREAD

**Issue by nils-werner** [thejasvibr/bat_beamshapes#6]
Hi, this issue is related to your submission to JOSS, [#3740](https://github.com/openjournals/joss-reviews/issues/3740).

I tried running the code example on https://beamshapes.readthedocs.io/en/latest/gallery_examples/0_preprint_figures.html

and it fails with 

```
Traceback (most recent call last):
  File "scribble.py", line 5, in <module>
    from beamshapes import piston_in_sphere_flint as piston_sphere # to speed things up!!
  File "/Users/nwerner/Projekte/beamshapes/bat_beamshapes/beamshapes/piston_in_sphere_flint.py", line 28, in <module>
    import flint
ModuleNotFoundError: No module named 'flint'
```

I would recommend to add and use [doctest](https://docs.python.org/3/library/doctest.html)s or [pytest doctest](https://docs.pytest.org/en/latest/how-to/doctest.html)s to ensure code examples are runnable and reproducible.

**Comment by thejasvibr** [comment]
This error was caused by an implementation of the piston in a sphere using the ```python-flint``` package, instead of the  ``` mpmath ``` package. The ```python-flint``` package is *extremely* fast (in comparison to ```mpmath```), but is tricky to install and  currently only available on Linux systems. In hindsight, perhaps it's not the most welcoming example - requiring users to go through a long installation. 

I've now done two things: 1) the 4 source model example does not require external dependency installation 2) made a separate example for more invested users who'd like to run the faster ```python-flint``` based implemention.
